name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:

  gocap:
    name: gocap
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ] # windows-latest,
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v3
        with: { go-version: 1.17.0 }
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod download
      - name: Install
        run: go install .

      - name: Check Capabilities
        run: gocap check .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: { version: latest }

      - name: Test
        run: go test ./...
