name: Release

on:
  release:
    types: [ published ]

jobs:
  gocap:
    name: gocap
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.17
        uses: actions/setup-go@v3
        with: { go-version: '1.17' }
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
